### ISSUE TITLE
support dicts of tables

### ISSUE THREAD

**Issue by markjoshwel** [markjoshwel/tomlantic#10]
```python
class Flight(BaseModel):
    ident: str
    fa_flight_id: str
    status: str
    blocked: bool
    diverted: bool
    cancelled: bool
    position_only: bool
    ...

class Config(BaseModel):
    api_aeroapi_url: str
    api_aeroapi_key: str
    api_telegram_hash: str
    api_telegram_id: int
    target_chat_id: int
    journey: list[str]
    flights: dict[str, Flight] = {}
```

the following pydantic model, of course, does work when adding new keys to flights
but er, dumping to toml results in:

```text
Traceback (most recent call last):
  File "C:\Users\mark\Works\phonyplane\main.py", line 388, in <module>
    playground()
  File "C:\Users\mark\Works\phonyplane\main.py", line 384, in playground
    config.model_dump_toml()
  File "C:\Users\mark\AppData\Local\pypoetry\Cache\virtualenvs\phonyplane-ShHeSTce-py3.12\Lib\site-packages\tomlantic\tomlantic.py", line 554, in model_dump_toml
    apply_model_differences(self.__original_model, self.model, document)
  File "C:\Users\mark\AppData\Local\pypoetry\Cache\virtualenvs\phonyplane-ShHeSTce-py3.12\Lib\site-packages\tomlantic\tomlantic.py", line 552, in apply_model_differences
    toml[cu_key] = cu_val
    ~~~~^^^^^^^^
  File "C:\Users\mark\AppData\Local\pypoetry\Cache\virtualenvs\phonyplane-ShHeSTce-py3.12\Lib\site-packages\tomlkit\container.py", line 633, in __setitem__
    self.append(key, value)
  File "C:\Users\mark\AppData\Local\pypoetry\Cache\virtualenvs\phonyplane-ShHeSTce-py3.12\Lib\site-packages\tomlkit\container.py", line 168, in append
    item = _item(item)
           ^^^^^^^^^^^
  File "C:\Users\mark\AppData\Local\pypoetry\Cache\virtualenvs\phonyplane-ShHeSTce-py3.12\Lib\site-packages\tomlkit\items.py", line 138, in item
    val[k] = item(v, _parent=val, _sort_keys=_sort_keys)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mark\AppData\Local\pypoetry\Cache\virtualenvs\phonyplane-ShHeSTce-py3.12\Lib\site-packages\tomlkit\items.py", line 212, in item
    raise ConvertError(f"Unable to convert an object of {type(value)} to a TOML item")
tomlkit.exceptions.ConvertError: Unable to convert an object of <class '__main__.Flight'> to a TOML item
```

because i was using the library pretty lazily i only encountered this now  
and funnily enough its on the front page of pydantic's docsite: https://docs.pydantic.dev/latest/#why-use-pydantic

**Comment by markjoshwel** [comment]
error lies here, probably just need to find out a way to get BaseModel inherited objects into a format understandable by tomlkit when we encounter them

https://github.com/markjoshwel/tomlantic/blob/0b0bbdc2974b1d7ce97de6571348afbc335a0baf/tomlantic/tomlantic.py#L516-L555

**Comment by markjoshwel** [comment]
experimenting with handling dicts because it seems ive only bothered to handle if a key's value is or isn't a BaseModel (see line 534 and 550 of the excerpt above)

since toml keys are always strings (https://github.com/toml-lang/toml/blob/main/toml.md#keys), i wonder what happens if:
1. there is a dict[int, Any] on pydantic's side
2. tomlantic coerces the int into a base or quoted key when dumping (we'll just error a new error, `TOMLKeyError` if its a non-hashable standard/primitive type anyways)
3. its dumped out
4. its read back in  
   (like will pydantic see the string and try to coerce it or just throw fists)

might spin this as another issue  
todo, future me :(

**Comment by markjoshwel** [comment]
okay no we do support dicts of tables:

https://github.com/markjoshwel/grassplain/blob/426ca523dff174b69a2d5e0f2cf9bde4b56721c0/src/grassplain/grassplain.py#L89

https://github.com/markjoshwel/grassplain/blob/426ca523dff174b69a2d5e0f2cf9bde4b56721c0/example-meadow.toml

so now i'll have to see whats up with this

**Comment by markjoshwel** [comment]
the issue lies with adding a BaseModel to the document and then dumping

this results in the if statement in apply_model_differences hitting the second branch and causing the ConvertError

**Comment by markjoshwel** [comment]
also: we validate the document twice, would there be any differences if we just deepcopy-ed the model?

**Comment by markjoshwel** [comment]
> also: we validate the document twice, would there be any differences if we just deepcopy-ed the model?

![image](https://github.com/user-attachments/assets/0c1e1c8f-c2dd-4a8d-85e6-9324e7363a63)

nope (still good practice though)

```python
class ModelBoundTOML(Generic[M]):
    def __init__(
        self,
        model: Type[M],
        document: TOMLDocument,
        handle_errors: bool = True,
    ) -> None:
        try:
            self.model = model.model_validate(document)

        except ValidationError as err:
            if not handle_errors:
                raise err

            handle_validation_error(err)

        # self.__original_model = model.model_validate(
        #     document
        # )  # if we pass the first validation, this should pass too
        self.__original_model = self.model.copy(deep=True)
        self.__document = document
 ```
 
 (use `self.model.copy(deep=True)`)

**Comment by markjoshwel** [comment]
OH DUDE I'M SO SILLY I FIGURED IT OUT

flighgs is a dict[str, BaseModel], so `og_val={}` and `cu_val={"...": Flight(...),...}`

we'll never hit the BaseModel isinstance check because i seem to have forgotten about tables of tables and by extension arrays of tables (#11)

loading of ToTs (and hopefully AoTs by extension) work because they don't interface with the document at all and is why grassplain works:

> okay no we do support dicts of tables / nested tables with unknown names at runtime:
> 
> https://github.com/markjoshwel/grassplain/blob/426ca523dff174b69a2d5e0f2cf9bde4b56721c0/src/grassplain/grassplain.py#L89
> 
> https://github.com/markjoshwel/grassplain/blob/426ca523dff174b69a2d5e0f2cf9bde4b56721c0/example-meadow.toml
> 
> so now i'll have to see whats up with this

but when we dump we try to convert a `dict[str, BaseModel]` and tomlkit doesn't know what to do with that

so next steps are to implement apply_table_of_table_differences and apply_array_of_table_differences functions to handle these incoming structures

**Comment by markjoshwel** [comment]
if it weren't for school this'd be done three days past the opening of this damn issue...

**Comment by markjoshwel** [comment]
reopening until 0.2.2
